import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync, readFileSync, readdirSync, statSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { dataDir } from "./state.ts";
import { redact, suspiciousSecret } from "./redact.ts";
export type Checkpoint = { session: string; branchLeaf: string; goals: string[]; files: string[]; createdAt: string };
const hash = (text: string) => createHash("sha256").update(text).digest("hex").slice(0, 24);
/** Keep branch-specific, redacted lightweight state. Pi remains the compactor. */
export function writeCheckpoint(value: Checkpoint, root = dataDir()): string | undefined {
  if ([...value.goals, ...value.files].some(suspiciousSecret)) return;
  const dir = join(root, "checkpoints"); mkdirSync(dir, { recursive: true, mode: 0o700 });
  const id = hash(`${value.session}\0${value.branchLeaf}`);
  // Session identifiers are generated by Pi but not automatically non-secret. Never persist them in cleartext.
  const contents = JSON.stringify({
    goals: value.goals.map(redact), files: value.files.map(redact), createdAt: value.createdAt,
  });
  writeFileSync(join(dir, `${id}.json`), contents, { mode: 0o600 });
  return id;
}
export function readCheckpoint(session: string, branchLeaf: string, root = dataDir()): Checkpoint | undefined {
  try {
    const id = hash(`${session}\0${branchLeaf}`);
    const parsed: unknown = JSON.parse(readFileSync(join(root, "checkpoints", `${id}.json`), "utf8"));
    if (!parsed || typeof parsed !== "object") return;
    const c = parsed as Checkpoint;
    if (!Array.isArray(c.goals) || !Array.isArray(c.files)) return;
    return { ...c, session, branchLeaf };
  } catch { return; }
}
export function checkpointFromBranch(session: string, branchLeaf: string, messages: string[]): Checkpoint {
  // Extract bounded, explicit markers only: no LLM summarizer or raw transcript dump.
  // Only the newest explicit user marker is a candidate; earlier plans may be canceled.
  // The extension requires an explicit user review before any candidate is reintroduced.
  const latest = messages.at(-1) ?? "";
  const goals = !suspiciousSecret(latest) && /\b(?:todo|next|goal|blocker|decision)\s*:/i.test(latest) && !/\b(?:cancel|ignore|never mind|no longer|scratch that|retract)\b/i.test(latest) ? [latest.slice(0, 500)] : [];
  const files = [...new Set((goals.length ? [latest] : []).filter(m => !suspiciousSecret(m)).flatMap(m => (m.match(/(?:^|\s)(?:\.?\.?\/)?[\w./-]+\.(?:ts|tsx|js|py|md|json)(?=\s|$)/g) ?? []).map(x => x.trim())))].slice(-25);
  return { session, branchLeaf, goals, files, createdAt: new Date().toISOString() };
}

export function pruneCheckpoints(retainDays: number, root = dataDir(), now = Date.now()): number {
  const dir = join(root, "checkpoints"); let count = 0;
  try {
    for (const file of readdirSync(dir)) {
      if (!/^[0-9a-f]{24}\.json$/.test(file)) continue;
      const target = join(dir, file);
      if (now - statSync(target).mtimeMs > retainDays * 86400000) { unlinkSync(target); count++; }
    }
  } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }
  return count;
}
