#!/usr/bin/env python3
"""Token Optimizer Windows launcher for Codex hooks.

Codex spawns ``command`` hooks through ``%COMSPEC% /C`` on native Windows,
and cmd.exe parses a /C command line ONCE, before anything on it runs:
``%VAR%`` expands to the pre-line value and ``setlocal
EnableDelayedExpansion`` only takes effect from the NEXT line, so no cmd
expansion form can carry a resolved marketplace version into the runner
path on the same line (issue #180). The pre-launcher fix embedded the
resolver as a base64 ``python -c`` exec-bootstrap,
which trips generic-loader antivirus signatures (issue #183): the match is
on the literal encoded-exec string, not on behavior, and a detection on an
install script surfaces as malware, not a warning.

This file is the replacement: a stable, readable .py that codex_install.py
copies NEXT TO the versioned install dirs (``.../token-optimizer/
windows-launcher.py``, a path that survives the marketplace swapping
``.../token-optimizer/<X.Y.Z>/`` on upgrade) and that baked hook commands
invoke by quoted path. Paths and arguments live as plainly quoted argv --
no encoded-exec string appears anywhere, and the cmd.exe single-parse
problem stays solved because nothing needs expanding.

Invocation contract (generated by codex_install._windows_launcher_command):

    python.exe "<parent>\\windows-launcher.py" --baked-root "<root>"
        [--env KEY=VALUE ...] -- <script> [args...] [MARKER]

* ``--baked-root`` is the install dir the command was generated from. It is
  the fail-open fallback only: the launcher rescans its sibling version
  dirs on every run and runs the NEWEST semver install, so hooks keep
  working after a marketplace upgrade prunes the baked one.
* ``--env KEY=VALUE`` applies per-hook environment (e.g.
  TOKEN_OPTIMIZER_NO_UPDATED_TOOL_OUTPUT=1) before dispatch.
* Everything after ``--`` is forwarded verbatim: ``sys.argv`` for the
  runner becomes ``[run.py, script, *args]`` and stdin passes through
  untouched. A trailing token equal to the generated-command ownership
  marker (token-optimizer/scripts/windows-launcher) is stripped, matching
  the old bootstrap, which dropped it when it replaced sys.argv.

Audit: the file IS the audit -- read it. For hooks.json entries baked by
the retired base64 launcher, ``codex_install.py --decode-launcher
"<command>"`` still decodes them.
"""

from __future__ import annotations

import os
import re
import runpy
import sys
from pathlib import Path

# Trailing ownership marker baked into every generated Windows launcher
# command (see codex_install._LAUNCHER_MARKER). It identifies the command
# to install/uninstall/doctor ownership checks and is never forwarded to
# the runner.
_LAUNCHER_MARKER = "token-optimizer/scripts/windows-launcher"

_SEMVER_DIR_RE = re.compile(r"\d+\.\d+\.\d+")

_USAGE = (
    "usage: windows-launcher.py --baked-root DIR [--env KEY=VALUE ...] "
    "-- SCRIPT [ARGS...]"
)


def _parse(argv: list[str]) -> tuple[str, list[str], str, list[str]]:
    """Split generated launcher argv into (baked_root, env, script, args).

    Manual parse, not argparse: hook arguments legitimately start with
    ``--`` (e.g. ``--quiet``), which argparse would misread as its own
    options. Everything after the ``--`` separator is positional.
    """
    baked_root = None
    env: list[str] = []
    i = 0
    while i < len(argv):
        token = argv[i]
        if token == "--":
            i += 1
            break
        if token in ("--baked-root", "--env") and i + 1 < len(argv):
            value = argv[i + 1]
            if token == "--baked-root":
                baked_root = value
            else:
                env.append(value)
            i += 2
            continue
        break  # unrecognized token: stop option parsing, rest is positional
    rest = argv[i:]
    if rest and rest[-1] == _LAUNCHER_MARKER:
        rest = rest[:-1]
    if not baked_root or not rest:
        raise SystemExit(_USAGE)
    return baked_root, env, rest[0], rest[1:]


def main(argv: list[str] | None = None) -> None:
    baked_root, env_pairs, script, args = _parse(
        sys.argv[1:] if argv is None else argv
    )
    root = Path(baked_root)
    baked = root
    # Resolve the newest semver sibling of the install parent; on any
    # listing failure keep the baked install (fail-open, same contract the
    # retired base64 bootstrap documented).
    try:
        versions = [p for p in root.parent.iterdir() if p.is_dir()
                    and _SEMVER_DIR_RE.fullmatch(p.name)]
        root = max(versions,
                   key=lambda p: tuple(map(int, p.name.split("."))),
                   default=root)
    except OSError:
        pass
    # The baked-install fallback is silent by design; the only observable
    # channel is a TOKEN_OPTIMIZER_DEBUG-gated line appended next to the
    # version dirs. A healthy semver resolve is not a fallback and never
    # logs.
    if root == baked and os.environ.get("TOKEN_OPTIMIZER_DEBUG"):
        try:
            with (root.parent / "token-optimizer-codex-resolver.log").open(
                "a", encoding="utf-8"
            ) as log:
                log.write(str(root) + "\n")
        except OSError:
            pass
    os.environ["TOKEN_OPTIMIZER_RUNTIME"] = "codex"
    os.environ["TOKEN_OPTIMIZER_RUNTIME_ROOT"] = str(root)
    for pair in env_pairs:
        key, sep, value = pair.partition("=")
        if sep and key:  # skip malformed pairs rather than breaking the hook
            os.environ[key] = value
    runner = root / "hooks" / "run.py"
    sys.argv = [str(runner), script, *args]
    sys.path.insert(0, str(runner.parent))
    runpy.run_path(str(runner), run_name="__main__")


if __name__ == "__main__":
    main()
